### ISSUE TITLE
Null Reference Exception for SerialController.IsOpen

### ISSUE THREAD

**Issue by cpellet** [akmadian/NZXTSharp#38]
![image](https://user-images.githubusercontent.com/18552249/59082112-14a9a180-8924-11e9-9d64-0668fc85e2c9.png)
![image](https://user-images.githubusercontent.com/18552249/59082124-2723db00-8924-11e9-9c96-53c3e0af3a6b.png)

**Comment by akmadian** [comment]
This only(?) occurs when the package is used from source instead of NuGet
